# Site settings
author: Wendy Kim
title: Data Science
header-img: img/home-bg.png
email: wendysjkim@gmail.com
copyright_name: Wendy Kim
description: > # this means to ignore newlines until "baseurl:"
  Wendy's Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wendysjkim

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
